apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-storage-loki-0
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: snapshot-storage-loki-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi